import colors from "tailwindcss/colors";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        zinc: {
          ...colors.zinc,
          150: "#ececed",
          250: "#dcdce0",
          350: "#bcbcc2",
          355: "#b8b8be",
          450: "#8b8b93",
          550: "#62626b",
          555: "#606068",
          650: "#494950",
          750: "#333338",
          850: "#1f1f22",
          855: "#1a1a1d",
        },
        emerald: {
          ...colors.emerald,
          450: "#22c68d",
          850: "#065640",
        },
        "on-secondary": "#ffffff",
        "surface-dim": "#e4e4e7",
        secondary: "#52525b",
        primary: "#09090b",
        "on-primary-fixed-variant": "#09090b",
        "primary-fixed": "#e4e4e7",
        "surface-container": "#f4f4f5",
        "secondary-fixed": "#e4e4e7",
        "primary-container": "#18181b",
        "star-rating": "#ffc107",
        "surface-container-low": "#fafafa",
        "on-tertiary-fixed": "#09090b",
        "secondary-container": "#f4f4f5",
        error: "#e11d48",
        "primary-fixed-dim": "#27272a",
        background: "#fafafa",
        "on-secondary-fixed-variant": "#27272a",
        "tertiary-fixed-dim": "#a1a1aa",
        tertiary: "#71717a",
        "sale-error": "#e11d48",
        "on-tertiary-container": "#f4f4f5",
        "on-error-container": "#4c0519",
        surface: "#ffffff",
        "tertiary-container": "#27272a",
        "surface-container-highest": "#e4e4e7",
        "surface-bright": "#ffffff",
        "deep-emerald": "#09090b",
        "on-error": "#ffffff",
        "error-container": "#ffe4e6",
        "on-tertiary-fixed-variant": "#27272a",
        "on-primary-fixed": "#09090b",
        "on-primary-container": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#f4f4f5",
        "on-background": "#09090b",
        "slate-blue": "#52525b",
        "on-secondary-container": "#18181b",
        "inverse-primary": "#ffffff",
        "on-surface-variant": "#52525b",
        "on-secondary-fixed": "#09090b",
        "outline-variant": "#e4e4e7",
        "on-primary": "#ffffff",
        outline: "#71717a",
        "surface-tint": "#09090b",
        "surface-lowest": "#ffffff",
        "surface-variant": "#f4f4f5",
        "inverse-surface": "#09090b",
        "secondary-fixed-dim": "#a1a1aa",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#ffffff",
        "surface-container-high": "#f4f4f5",
        "on-surface": "#09090b",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-xl": "64px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "margin-desktop": "32px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter Variable", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Inter Variable", "Inter", "sans-serif"],
        "body-lg": ["Inter Variable", "Inter", "sans-serif"],
        "title-md": ["Inter Variable", "Inter", "sans-serif"],
        "price-lg": ["Inter Variable", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter Variable", "Inter", "sans-serif"],
        "label-md": ["Inter Variable", "Inter", "sans-serif"],
        "title-lg": ["Inter Variable", "Inter", "sans-serif"],
        "headline-lg": ["Inter Variable", "Inter", "sans-serif"],
        "display-lg": ["Inter Variable", "Inter", "sans-serif"],
        "body-md": ["Inter Variable", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "20px",
          { lineHeight: "28px", fontWeight: "600", letterSpacing: "-0.01em" },
        ],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": [
          "15px",
          { lineHeight: "22px", fontWeight: "600", letterSpacing: "-0.01em" },
        ],
        "price-lg": [
          "24px",
          { lineHeight: "28px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "label-md": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" },
        ],
        "title-lg": [
          "18px",
          { lineHeight: "24px", fontWeight: "600", letterSpacing: "-0.01em" },
        ],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
