/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadd",
        "secondary": "#4e6073",
        "primary": "#005228",
        "on-primary-fixed-variant": "#005228",
        "primary-fixed": "#9bf6b2",
        "surface-container": "#eceef1",
        "secondary-fixed": "#d1e4fb",
        "primary-container": "#006d37",
        "star-rating": "#fbbf24",
        "surface-container-low": "#f2f4f7",
        "on-tertiary-fixed": "#111e1f",
        "secondary-container": "#d1e4fb",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#80d997",
        "background": "#f7f9fc",
        "on-secondary-fixed-variant": "#37485b",
        "tertiary-fixed-dim": "#bbc9ca",
        "tertiary": "#3d494a",
        "sale-error": "#ba1a1a",
        "on-tertiary-container": "#cedcdc",
        "on-error-container": "#93000a",
        "surface": "#f7f9fc",
        "tertiary-container": "#546162",
        "surface-container-highest": "#e0e3e6",
        "surface-bright": "#f7f9fc",
        "deep-emerald": "#006d37",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#3c494a",
        "on-primary-fixed": "#00210c",
        "on-primary-container": "#91eca8",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d7e5e6",
        "on-background": "#191c1e",
        "slate-blue": "#4e6073",
        "on-secondary-container": "#546679",
        "inverse-primary": "#80d997",
        "on-surface-variant": "#3f4940",
        "on-secondary-fixed": "#091d2d",
        "outline-variant": "#becabd",
        "on-primary": "#ffffff",
        "outline": "#6f7a6f",
        "surface-tint": "#006d37",
        "surface-lowest": "#ffffff",
        "surface-variant": "#e0e3e6",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#b6c8de",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "surface-container-high": "#e6e8eb",
        "on-surface": "#191c1e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "12px",
        "xl": "16px",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "stack-xl": "80px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "48px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "price-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "price-lg": ["28px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
